version: '3.8'

services:
  ctfd:
    build: .
    ports:
      - "8080:8000"
    volumes:
      - ctfd-data:/opt/CTFd
      - ./challenges:/opt/CTFd/challenges
    container_name: ctf_challenge_server
    restart: unless-stopped

volumes:
  ctfd-data:
